apiVersion: v1
kind: Pod
metadata:
  name: ip-app
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app
    ports:
    - containerPort: 80
  env:
    - name: DB_URL
      valueFrom:
        configMapKeyRef:
          name: pod-configmap
          key: db_url
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: pod-configmap
          key: db_user
