apiVersion: v1
kind: Pod
metadata:
  name: ip-app-secret
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app
    ports:
    - containerPort: 80
    env:
    - name: DB_URL
      valueFrom:
        secretKeyRef:
          name: pod-secret
          key: db_url
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: pod-configmap
          key: db_user
