apiVersion: v1
kind: Pod
metadata:
  name: ip-app
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app
    ports:
    - containerPort: 80
  tolerations:
  - key: "mytaint"
    operator: "Equal"
    value: "NewTaint"
    effect: "NoSchedule"
