apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app
  labels:
    app: ip-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      containers:
      - name: ip-app
        image: harshajain/ip_app
        ports:
        - containerPort: 80
